# Generated by Django 3.2.9 on 2024-12-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_alter_room_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Подтверждено'), ('CANCELLED', 'Отменено'), ('PROCESSING', 'Обрабатывается')], default='PROCESSING', max_length=50, verbose_name='Статус'),
        ),
    ]
