# Generated by Django 3.2.9 on 2024-12-20 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='start',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='model.hotel'),
        ),
    ]
